---
# tasks file for pieterjvrensburg.yumlocal/
- file: dest={{package_dest}} state=directory

- name: copy package files
  copy: src={{package_src}}/* dest={{package_dest}}

- name: install createrepo command
  yum: name=createrepo state=present

- name: create local yum repository
  command: createrepo {{package_dest}}

- name: create yum repo files
  template:
    src: custom.repo.j2
    dest: /etc/yum.repos.d/custom.repo
    owner: root
    group: root
    mode: 0644

- name: install packages
  yum: name={{item}} state=present
  with_items: "{{package_list}}"
